apiVersion: 1

datasources:
  - name: GitHub Metrics
    type: postgres
    url: postgres:5432
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1600
    isDefault: true
